title: Weathour' blog
author: Weathour
email: 1205387329@qq.com
description: Weathour' blog.
show_excerpts: true 

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 围琐
  tagline: 学生，QQ:1205387329
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  social_links:
    github:  weathour
    rss: rss
 
